import type { FamilyData, PatientId } from "./types";

export const SEED_DATA: FamilyData = {
  activePatientId: "mother",
  notifications: [
    {
      id: "n1",
      message: "Creatinine slightly increased in latest kidney panel",
      timestamp: "2025-07-28T10:30:00Z",
      patientId: "mother",
      type: "alert",
    },
    {
      id: "n2",
      message: "Report received via WhatsApp from Mom",
      timestamp: "2025-07-25T14:20:00Z",
      patientId: "mother",
      type: "whatsapp",
    },
  ],
  patients: {
    mother: {
      patient: {
        id: "mother",
        name: "Lakshmi Devi",
        age: 68,
        relationship: "Mother",
        bloodGroup: "B+",
        avatar: "LD",
        conditions: [
          "Type II Diabetes Mellitus",
          "Chronic Kidney Disease (Stage 3)",
          "Diabetic Retinopathy",
        ],
        allergies: ["Penicillin", "Sulfa drugs"],
        surgeries: ["Cataract surgery (2022, left eye)", "Appendectomy (1998)"],
        emergencyContacts: [
          { name: "Rajesh Kumar", relation: "Son", phone: "+91 98765 43210" },
          { name: "Priya Sharma", relation: "Daughter", phone: "+91 98765 43211" },
        ],
        insurance: {
          provider: "Star Health Insurance",
          policyNumber: "SH-2024-884521",
          groupNumber: "FAM-001",
        },
      },
      timeline: [
        {
          id: "t1",
          patientId: "mother",
          date: "2021-03-15",
          year: 2021,
          type: "diagnosis",
          title: "Diagnosed Type II Diabetes",
          description:
            "HbA1c 8.2%. Fasting glucose 165 mg/dL. Dr. Mehta recommended lifestyle changes and Metformin.",
          doctor: "Dr. Anil Mehta",
          hospital: "Apollo Hospitals, Chennai",
          confidence: 95,
          verified: true,
        },
        {
          id: "t2",
          patientId: "mother",
          date: "2021-04-01",
          year: 2021,
          type: "medication",
          title: "Started Metformin 500mg",
          description: "Twice daily with meals. Initial dose for glycemic control.",
          doctor: "Dr. Anil Mehta",
          confidence: 98,
          verified: true,
        },
        {
          id: "t3",
          patientId: "mother",
          date: "2022-06-20",
          year: 2022,
          type: "procedure",
          title: "Annual Eye Examination",
          description:
            "Early signs of diabetic retinopathy detected. Referred to ophthalmologist.",
          doctor: "Dr. Priya Nair",
          hospital: "Sankara Eye Hospital",
          confidence: 92,
          verified: true,
        },
        {
          id: "t4",
          patientId: "mother",
          date: "2023-01-10",
          year: 2023,
          type: "complication",
          title: "Eye Complications — Diabetic Retinopathy",
          description:
            "Mild non-proliferative diabetic retinopathy. Laser treatment recommended if progression continues.",
          doctor: "Dr. Priya Nair",
          hospital: "Sankara Eye Hospital",
          confidence: 94,
          verified: true,
        },
        {
          id: "t5",
          patientId: "mother",
          date: "2023-08-05",
          year: 2023,
          type: "medication",
          title: "Insulin Added — Glargine 10 units",
          description:
            "HbA1c remained at 7.8% despite oral medications. Basal insulin initiated at bedtime.",
          doctor: "Dr. Anil Mehta",
          confidence: 96,
          verified: true,
        },
        {
          id: "t6",
          patientId: "mother",
          date: "2024-11-12",
          year: 2024,
          type: "lab",
          title: "Kidney Function Decline Noted",
          description:
            "eGFR dropped to 52 mL/min (previously 58). Creatinine 1.4 mg/dL. Nephrology referral suggested.",
          doctor: "Dr. Anil Mehta",
          hospital: "Apollo Hospitals, Chennai",
          confidence: 91,
          verified: true,
        },
        {
          id: "t7",
          patientId: "mother",
          date: "2025-07-28",
          year: 2025,
          type: "lab",
          title: "Kidney Markers Worsening",
          description:
            "Creatinine 1.6 mg/dL (↑ from 1.4). eGFR 48 mL/min. Albuminuria present. CKD Stage 3 confirmed.",
          doctor: "Dr. Kavitha Reddy",
          hospital: "Apollo Hospitals, Chennai",
          relatedReportId: "r5",
          confidence: 88,
          verified: false,
        },
      ],
      medications: [
        {
          id: "m1",
          name: "Metformin",
          dosage: "1000mg",
          frequency: "Twice daily",
          prescribedBy: "Dr. Anil Mehta",
          startDate: "2021-04-01",
          status: "active",
          confidence: 98,
        },
        {
          id: "m2",
          name: "Insulin Glargine",
          dosage: "12 units",
          frequency: "Once daily at bedtime",
          prescribedBy: "Dr. Anil Mehta",
          startDate: "2023-08-05",
          status: "active",
          confidence: 96,
        },
        {
          id: "m3",
          name: "Atorvastatin",
          dosage: "10mg",
          frequency: "Once daily",
          prescribedBy: "Dr. Anil Mehta",
          startDate: "2022-01-15",
          status: "active",
          confidence: 94,
        },
        {
          id: "m4",
          name: "Losartan",
          dosage: "50mg",
          frequency: "Once daily",
          prescribedBy: "Dr. Kavitha Reddy",
          startDate: "2025-01-20",
          status: "active",
          confidence: 72,
        },
      ],
      reports: [
        {
          id: "r1",
          patientId: "mother",
          title: "Initial Diabetes Diagnosis Report",
          summary:
            "Comprehensive metabolic panel confirming Type II Diabetes. HbA1c 8.2%, elevated fasting glucose.",
          uploadedAt: "2021-03-20T09:00:00Z",
          reportDate: "2021-03-15",
          source: "upload",
          thumbnailColor: "#E8F5E9",
          confidence: 95,
          entities: [
            { type: "diagnosis", value: "Type II Diabetes Mellitus", confidence: 96 },
            { type: "lab", value: "HbA1c: 8.2%", confidence: 94 },
            { type: "lab", value: "Fasting Glucose: 165 mg/dL", confidence: 93 },
            { type: "doctor", value: "Dr. Anil Mehta", confidence: 98 },
            { type: "hospital", value: "Apollo Hospitals, Chennai", confidence: 97 },
            { type: "medicine", value: "Metformin 500mg", confidence: 95 },
          ],
          labValues: [
            { name: "HbA1c", value: "8.2", unit: "%", referenceRange: "4.0-5.6" },
            { name: "Fasting Glucose", value: "165", unit: "mg/dL", referenceRange: "70-100" },
          ],
          verifiedEntities: ["Type II Diabetes Mellitus", "Metformin 500mg"],
        },
        {
          id: "r2",
          patientId: "mother",
          title: "Ophthalmology — Retinopathy Assessment",
          summary:
            "Fundoscopy reveals mild non-proliferative diabetic retinopathy. No macular edema.",
          uploadedAt: "2023-01-15T11:30:00Z",
          reportDate: "2023-01-10",
          source: "upload",
          thumbnailColor: "#FFF3E0",
          confidence: 92,
          entities: [
            { type: "diagnosis", value: "Diabetic Retinopathy (mild NPDR)", confidence: 91 },
            { type: "doctor", value: "Dr. Priya Nair", confidence: 97 },
            { type: "hospital", value: "Sankara Eye Hospital", confidence: 96 },
            { type: "followup", value: "Repeat examination in 6 months", confidence: 88 },
          ],
          labValues: [],
          verifiedEntities: ["Diabetic Retinopathy (mild NPDR)"],
        },
        {
          id: "r3",
          patientId: "mother",
          title: "Endocrinology Follow-up",
          summary:
            "HbA1c 7.8% despite dual oral therapy. Insulin Glargine initiated.",
          uploadedAt: "2023-08-10T14:00:00Z",
          reportDate: "2023-08-05",
          source: "upload",
          thumbnailColor: "#E3F2FD",
          confidence: 94,
          entities: [
            { type: "medicine", value: "Insulin Glargine 10 units", confidence: 93 },
            { type: "lab", value: "HbA1c: 7.8%", confidence: 95 },
            { type: "doctor", value: "Dr. Anil Mehta", confidence: 98 },
          ],
          labValues: [
            { name: "HbA1c", value: "7.8", unit: "%", referenceRange: "4.0-5.6", trend: "down", previousValue: "8.2" },
          ],
          verifiedEntities: ["Insulin Glargine 10 units"],
        },
        {
          id: "r4",
          patientId: "mother",
          title: "Kidney Function Panel — Nov 2024",
          summary:
            "Moderate decline in eGFR. Creatinine trending upward. Nephrology consultation recommended.",
          uploadedAt: "2024-11-15T10:00:00Z",
          reportDate: "2024-11-12",
          source: "whatsapp",
          thumbnailColor: "#FCE4EC",
          confidence: 89,
          entities: [
            { type: "lab", value: "Creatinine: 1.4 mg/dL", confidence: 92 },
            { type: "lab", value: "eGFR: 52 mL/min", confidence: 90 },
            { type: "followup", value: "Nephrology referral", confidence: 85 },
          ],
          labValues: [
            { name: "Creatinine", value: "1.4", unit: "mg/dL", referenceRange: "0.6-1.2", trend: "up", previousValue: "1.1" },
            { name: "eGFR", value: "52", unit: "mL/min", referenceRange: ">60", trend: "down", previousValue: "58" },
          ],
          verifiedEntities: [],
        },
        {
          id: "r5",
          patientId: "mother",
          title: "Nephrology Panel — July 2025",
          summary:
            "CKD Stage 3 confirmed. Creatinine increased to 1.6 mg/dL. Losartan initiated for renal protection.",
          uploadedAt: "2025-07-28T10:30:00Z",
          reportDate: "2025-07-28",
          source: "whatsapp",
          thumbnailColor: "#F3E5F5",
          confidence: 78,
          entities: [
            { type: "diagnosis", value: "CKD Stage 3", confidence: 85 },
            { type: "lab", value: "Creatinine: 1.6 mg/dL", confidence: 88 },
            { type: "lab", value: "eGFR: 48 mL/min", confidence: 86 },
            { type: "medicine", value: "Losartan 50mg", confidence: 72, needsVerification: true },
            { type: "doctor", value: "Dr. Kavitha Reddy", confidence: 90 },
          ],
          labValues: [
            { name: "Creatinine", value: "1.6", unit: "mg/dL", referenceRange: "0.6-1.2", trend: "up", previousValue: "1.4" },
            { name: "eGFR", value: "48", unit: "mL/min", referenceRange: ">60", trend: "down", previousValue: "52" },
            { name: "Urine Albumin", value: "45", unit: "mg/g", referenceRange: "<30", trend: "up" },
          ],
          verifiedEntities: [],
        },
      ],
      appointments: [
        {
          id: "a1",
          patientId: "mother",
          title: "Nephrology Follow-up",
          doctor: "Dr. Kavitha Reddy",
          hospital: "Apollo Hospitals, Chennai",
          date: "2025-08-15",
          time: "10:00 AM",
        },
        {
          id: "a2",
          patientId: "mother",
          title: "Eye Checkup",
          doctor: "Dr. Priya Nair",
          hospital: "Sankara Eye Hospital",
          date: "2025-09-02",
          time: "2:30 PM",
        },
      ],
    },
    father: {
      patient: {
        id: "father",
        name: "Ramesh Kumar",
        age: 72,
        relationship: "Father",
        bloodGroup: "O+",
        avatar: "RK",
        conditions: [
          "Essential Hypertension",
          "Coronary Artery Disease",
          "Hyperlipidemia",
        ],
        allergies: ["Aspirin (GI upset)"],
        surgeries: [
          "Coronary Angioplasty with Stent (2020)",
          "Hernia Repair (2015)",
        ],
        emergencyContacts: [
          { name: "Rajesh Kumar", relation: "Son", phone: "+91 98765 43210" },
          { name: "Priya Sharma", relation: "Daughter", phone: "+91 98765 43211" },
        ],
        insurance: {
          provider: "Star Health Insurance",
          policyNumber: "SH-2024-884522",
          groupNumber: "FAM-001",
        },
      },
      timeline: [
        {
          id: "ft1",
          patientId: "father",
          date: "2018-05-10",
          year: 2018,
          type: "diagnosis",
          title: "Diagnosed Hypertension",
          description: "BP consistently 150/95. Started on Amlodipine 5mg.",
          doctor: "Dr. Suresh Iyer",
          hospital: "Fortis Hospital, Bangalore",
          confidence: 96,
          verified: true,
        },
        {
          id: "ft2",
          patientId: "father",
          date: "2020-02-14",
          year: 2020,
          type: "procedure",
          title: "Coronary Angioplasty",
          description:
            "70% LAD stenosis. Drug-eluting stent placed. Post-procedure recovery uneventful.",
          doctor: "Dr. Venkat Raman",
          hospital: "Narayana Health, Bangalore",
          confidence: 97,
          verified: true,
        },
        {
          id: "ft3",
          patientId: "father",
          date: "2022-09-20",
          year: 2022,
          type: "medication",
          title: "Added Clopidogrel",
          description: "Dual antiplatelet therapy post-stent. Aspirin discontinued due to GI issues.",
          doctor: "Dr. Venkat Raman",
          confidence: 93,
          verified: true,
        },
        {
          id: "ft4",
          patientId: "father",
          date: "2025-03-08",
          year: 2025,
          type: "lab",
          title: "Lipid Panel — Elevated LDL",
          description: "LDL 142 mg/dL despite statin therapy. Dose adjustment recommended.",
          doctor: "Dr. Suresh Iyer",
          hospital: "Fortis Hospital, Bangalore",
          confidence: 90,
          verified: true,
        },
      ],
      medications: [
        {
          id: "fm1",
          name: "Amlodipine",
          dosage: "10mg",
          frequency: "Once daily",
          prescribedBy: "Dr. Suresh Iyer",
          startDate: "2018-05-10",
          status: "active",
          confidence: 97,
        },
        {
          id: "fm2",
          name: "Atorvastatin",
          dosage: "40mg",
          frequency: "Once daily at night",
          prescribedBy: "Dr. Suresh Iyer",
          startDate: "2018-06-01",
          status: "active",
          confidence: 95,
        },
        {
          id: "fm3",
          name: "Clopidogrel",
          dosage: "75mg",
          frequency: "Once daily",
          prescribedBy: "Dr. Venkat Raman",
          startDate: "2022-09-20",
          status: "active",
          confidence: 94,
        },
        {
          id: "fm4",
          name: "Metoprolol",
          dosage: "25mg",
          frequency: "Twice daily",
          prescribedBy: "Dr. Venkat Raman",
          startDate: "2020-02-14",
          status: "active",
          confidence: 96,
        },
      ],
      reports: [
        {
          id: "fr1",
          patientId: "father",
          title: "Cardiology — Post Angioplasty Report",
          summary:
            "Successful PCI with drug-eluting stent to LAD. Ejection fraction 55%.",
          uploadedAt: "2020-02-20T08:00:00Z",
          reportDate: "2020-02-14",
          source: "upload",
          thumbnailColor: "#FFEBEE",
          confidence: 96,
          entities: [
            { type: "procedure", value: "Coronary Angioplasty with DES", confidence: 97 },
            { type: "doctor", value: "Dr. Venkat Raman", confidence: 98 },
            { type: "hospital", value: "Narayana Health, Bangalore", confidence: 96 },
          ],
          labValues: [
            { name: "Ejection Fraction", value: "55", unit: "%", referenceRange: ">55" },
          ],
          verifiedEntities: ["Coronary Angioplasty with DES"],
        },
        {
          id: "fr2",
          patientId: "father",
          title: "Lipid Profile — March 2025",
          summary: "LDL cholesterol elevated at 142 mg/dL. Statin dose increase under consideration.",
          uploadedAt: "2025-03-10T09:00:00Z",
          reportDate: "2025-03-08",
          source: "upload",
          thumbnailColor: "#E8EAF6",
          confidence: 91,
          entities: [
            { type: "lab", value: "LDL: 142 mg/dL", confidence: 93 },
            { type: "lab", value: "HDL: 38 mg/dL", confidence: 92 },
            { type: "doctor", value: "Dr. Suresh Iyer", confidence: 95 },
          ],
          labValues: [
            { name: "LDL Cholesterol", value: "142", unit: "mg/dL", referenceRange: "<100", trend: "up", previousValue: "128" },
            { name: "HDL Cholesterol", value: "38", unit: "mg/dL", referenceRange: ">40", trend: "stable" },
          ],
          verifiedEntities: [],
        },
      ],
      appointments: [
        {
          id: "fa1",
          patientId: "father",
          title: "Cardiology Review",
          doctor: "Dr. Venkat Raman",
          hospital: "Narayana Health, Bangalore",
          date: "2025-08-20",
          time: "11:00 AM",
        },
      ],
    },
  },
};

export function getPatientIds(): PatientId[] {
  return ["mother", "father"];
}
